# %% [markdown]
# ## Two-Phase Fine-Tuning: Train -> Nudge
#
# First train a LoRA adapter on the full dataset (minus the portion of easy
# samples held out for nudging), then nudge it with a "hard-heavy" mixed set to
# push accuracy on the hard problem types higher without forgetting the easy ones.
#
# **Phase 1 - Train:** all hard problems + the easy problems not held out for nudging.
# **Phase 2 - Nudge:** all hard problems + n samples of each easy type (n = the count of the smallest hard type).

# %%
# ════════════════════════════════════════════════════════════════════════════
#  Global config (all the "value judgments" of the whole approach live here)   see docs/solution.md §1
# ════════════════════════════════════════════════════════════════════════════
import os, sys

# Kaggle's default log encoding may not be utf-8, and the chain-of-thought
# contains non-ASCII characters such as ⌈⌉ and Greek letters; without forcing
# utf-8 they trigger a UnicodeEncodeError on print. These lines are pure
# defense and unrelated to the algorithm.
os.environ["PYTHONIOENCODING"] = "utf-8"
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="strict")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="strict")

SEED              = 42                                            # Fixed random seed throughout, for reproducibility
BASE_MODEL_NAME   = "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16"  # Competition-mandated base model (must be written back to config on submission, see end)
# ⚠️ The data is NOT the official train.csv (which only has id/prompt/answer);
#    it is a third-party dataset with an extra generated_cot column -- a
#    chain-of-thought solution already generated by others. This script only
#    does the "student-side" distillation.
DATASET_PATH      = "/kaggle/input/datasets/dgxchen/nemotron-cot-tong/problem_ids_matched.csv"

# The core bet of the whole approach: treat these three types as the "hard"
# problems and train them heavily in both phases.   see §1.1
#   - cryptarithm_deduce / cryptarithm_guess: letter arithmetic, both subtypes hard
#   - equation_numeric_guess: among numeric-equation problems only the guess subtype is hard (deduce is not)
HARD_TYPES        = {"cryptarithm_deduce", "cryptarithm_guess", "equation_numeric_guess"}

# At evaluation time the host automatically appends a "put the answer inside
# \boxed{}" instruction after the problem. We append the same suffix during
# training so that "training input ≈ evaluation input". If the input
# distributions are misaligned, the model may not faithfully emit \boxed{} at
# inference.  see §1.2
PROMPT_SUFFIX     = '\nPlease put your final answer inside `\\boxed{}`. For example: `\\boxed{your answer}`'

# ── LoRA config ──────────────────────────────────────────────────────────────
LORA_RANK    = 32        # Competition rule caps rank ≤ 32; max it out: more capacity holds more of the patterns to memorize
LORA_ALPHA   = 32        # alpha/rank = 1.0, scaling factor of 1, no amplification
LORA_DROPOUT = 0.0       # Dropout off during training: distillation must replicate traces precisely, prefer overfitting to learn accurately   see §1.3
# Note in_proj/out_proj -- these are the projections of the Mamba-2 (SSM)
# blocks, which a standard Llama LoRA recipe does not have!
# q/k/v/o_proj are the Attention layers, up/down_proj are the MoE/MLP layers.
# Covering all three layer kinds mirrors the hybrid architecture.
TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj",
                  "in_proj", "out_proj", "up_proj", "down_proj"] # lm_head is excluded: saves rank budget + changing the output layer is risky

# ── Phase 1 "Train": aggressive coarse training, optimizing coverage and speed ───────────────────────────────  see §7
TRAIN_LR            = 2e-4    # Large learning rate, hammer the traces hard into the LoRA
TRAIN_BATCH         = 1       # One sample per GPU (the 30B model is memory-tight)
TRAIN_GRAD_ACCUM    = 8       # Gradient accumulation of 8 steps -> effective batch = 1×8 = 8
TRAIN_EPOCHS        = 1       # One pass over the data only

# ── Phase 2 "Nudge": small-step refinement, optimizing hard-problem accuracy and stability ──────────────────────────  see §8
NUDGE_LR            = 5e-6    # Tiny learning rate, 1/40 of Phase 1, only "nudge" rather than overturn
NUDGE_BATCH         = 1
NUDGE_GRAD_ACCUM    = 8
NUDGE_EPOCHS        = 1

print("Config loaded.")
print(f"  Hard types: {HARD_TYPES}")
print(f"  Phase 1: lr={TRAIN_LR}, batch={TRAIN_BATCH}, accum={TRAIN_GRAD_ACCUM}")
print(f"  Phase 2: lr={NUDGE_LR},  batch={NUDGE_BATCH}, accum={NUDGE_GRAD_ACCUM}")


# %% [markdown]
# ## Setup

# %%
# ════════════════════════════════════════════════════════════════════════════
#  Environment patches (pure engineering pitfalls: new model + new Blackwell hardware + no internet)   see docs/solution.md §2
#  These "ugly" sections are justified -- they reflect the real barrier to entry in the competition: whoever gets the environment running first is ahead.
# ════════════════════════════════════════════════════════════════════════════
import os, glob, sys, subprocess, site

# The Kaggle evaluation environment has no internet, so every dependency must be
# found in a mounted offline dataset and installed from a local .whl.
candidates = glob.glob("/kaggle/input/**/*triton*.whl", recursive=True)  # Find the Triton wheel under the mounted directory
print("Found Triton wheels:", candidates)
if not candidates:
    raise FileNotFoundError("No Triton wheel found under /kaggle/input")
wheel = candidates[0]

# Install into a separate directory and prepend it to sys.path, to avoid
# polluting / overwriting the system's bundled package versions.
target = "/kaggle/working/pydeps"
os.makedirs(target, exist_ok=True)
subprocess.run(
    [sys.executable, "-m", "pip", "install",
     "--no-deps", "--target", target, "--upgrade", "--ignore-installed", wheel],  # --no-deps: install only itself, do not touch dependencies
    check=True,
)
if target not in sys.path:
    sys.path.insert(0, target)     # Make this session prefer the Triton in this directory
site.addsitedir(target)
print("Triton installed.")


# %%
# ── ptxas patch for the Blackwell GPU ────────────────────────────────────────
#  The ptxas that ships with Triton (the tool that assembles PTX into GPU
#  machine code) does not yet support the new Blackwell architecture; here we
#  swap in a ptxas binary that can run on Blackwell and trick Triton's version check.
import sys, os, shutil, stat

sys.path.insert(0, '/kaggle/usr/lib/notebooks/ryanholbrook/nvidia_utility_script')  # Host-provided utility-script directory

# Copy the Blackwell ptxas to /tmp and add execute permission (the dataset mount is usually read-only and cannot be chmod-ed directly)
ptxas_src = '/kaggle/usr/lib/notebooks/ryanholbrook/nvidia_utility_script/triton/backends/nvidia/bin/ptxas-blackwell'
ptxas_dst = '/tmp/ptxas-blackwell'
if os.path.exists(ptxas_src) and not os.path.exists(ptxas_dst):
    shutil.copy2(ptxas_src, ptxas_dst)
    os.chmod(ptxas_dst, os.stat(ptxas_dst).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)  # +x executable
    # Copy the whole bin directory too and make everything executable
    src_bin = os.path.dirname(ptxas_src)
    dst_bin = '/tmp/triton_nvidia_bin'
    shutil.copytree(src_bin, dst_bin, dirs_exist_ok=True)
    for f in os.listdir(dst_bin):
        fp = os.path.join(dst_bin, f)
        if os.path.isfile(fp):
            os.chmod(fp, os.stat(fp).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    os.environ["TRITON_PTXAS_BLACKWELL_PATH"] = ptxas_dst
    import triton.backends.nvidia as nv_backend
    nv_backend.__file__ = os.path.join(dst_bin, '..', '__init__.py')   # Point Triton's backend at the new bin directory
    os.environ["TRITON_PTXAS_PATH"] = ptxas_dst

# Monkey-patch: make Triton report a ptxas version of 12.0, skipping its check against the real version.
import triton.backends.nvidia.compiler as nv_compiler
nv_compiler.get_ptxas_version = lambda arch: '12.0'
print("Training environment fixes applied.")


# %%
# ── Offline install of training dependencies ───────────────────────────────────────
import glob, os, subprocess, sys
import torch

print("Python:", sys.version)
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if not torch.cuda.is_available():
    raise RuntimeError("GPU runtime required.")   # No GPU, stop immediately rather than waste a run

# Install the core training stack from the offline dataset as well (--no-index fully disables networking, --find-links points at the local wheel directory)
packages_dir = "/kaggle/input/datasets/mayukh18/nemotron-packages/packages"
if not os.path.isdir(packages_dir):
    raise FileNotFoundError(f"Offline wheel directory not found: {packages_dir}")

subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q",
     "--no-index", "--find-links", packages_dir,
     "unsloth", "trl", "peft", "transformers", "datasets", "accelerate", "bitsandbytes"],  # The full training toolkit
    check=True,
)

# The Mamba-specific CUDA kernels must be installed separately (mandatory for
# the hybrid architecture, otherwise the SSM layers will not run).
# When several versions exist, take the last after sorting (usually the newest).
def _pick_last(pattern):
    wheels = sorted(glob.glob(f"/kaggle/input/**/{pattern}", recursive=True))
    return wheels[-1] if wheels else None

for wheel in [_pick_last("causal*conv1d*.whl"), _pick_last("mamba_ssm-*.whl")]:  # The two key Mamba kernels
    if wheel:
        print("Installing:", wheel)
        subprocess.run([sys.executable, "-m", "pip", "install", "--no-index", "--no-deps", wheel], check=True)
    else:
        raise FileNotFoundError("Required wheel not found.")

print("All packages installed.")


# %% [markdown]
# ## Load Base Model

# %%
# ════════════════════════════════════════════════════════════════════════════
#  Load the base model + attach LoRA                            see docs/solution.md §3
# ════════════════════════════════════════════════════════════════════════════
import torch
import kagglehub
from unsloth import FastLanguageModel   # Unsloth: an HF wrapper optimized for memory/speed

MODEL_PATH = kagglehub.model_download("metric/nemotron-3-nano-30b-a3b-bf16/transformers/default")  # Pull the base model from the Kaggle cache
print(f"Model path: {MODEL_PATH}")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_PATH,
    max_seq_length=8192,        # Align with the evaluation max_model_len=8192; the model natively supports 1M but we deliberately cap it at 8192
    load_in_4bit=False,         # No quantization ...
    load_in_8bit=False,         # ... pure BF16 training: quantization loses precision, but this task needs exact trace replication
    full_finetuning=False,      # No full-parameter fine-tuning, train only LoRA
    trust_remote_code=True,     # Nemotron uses custom modeling code (hybrid architecture), which must be allowed
    unsloth_force_compile=False,
    attn_implementation="eager",# Use the most basic attention: under a new model + new hardware, optimized implementations like FlashAttention are not yet stable
    dtype=torch.bfloat16,
)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token   # The model defines no pad token, so use eos in its place (standard practice)
print("Base model loaded.")


# %%
from unsloth import FastLanguageModel

# Actually attach the §1.3 LoRA config to the base model, yielding a PEFT model that trains only the LoRA delta.
model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_RANK,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=TARGET_MODULES,
    bias="none",                              # Do not train bias terms
    use_gradient_checkpointing="unsloth",     # Unsloth's memory-saving gradient checkpointing, essentially mandatory for a model this large
    random_state=SEED,
)
model.print_trainable_parameters()            # Print the trainable parameter count: you will see it is only a tiny fraction of the total


# %% [markdown]
# ## Dataset Split
#
# Split into two non-overlapping training sets:
# - **Epoch 1 set**: all hard problems + the easy problems not drawn for nudging
# - **Nudge set**: all hard problems + n samples of each easy type (n = the count of the smallest hard type)

# %%
# ════════════════════════════════════════════════════════════════════════════
#  Dataset split: into two "non-overlapping" training sets                see docs/solution.md §4
#    Epoch1 set (for Phase 1) = all hard problems + most easy problems
#    Nudge set  (for Phase 2) = all hard problems + n fresh samples of each easy type (type-balanced)
# ════════════════════════════════════════════════════════════════════════════
import pandas as pd, random, re
from collections import defaultdict

df       = pd.read_csv(DATASET_PATH)
train_df = df.sample(frac=1, random_state=SEED).reset_index(drop=True)   # Shuffle the whole thing; fixed seed keeps it reproducible
print(f"Total dataset: {len(train_df)} rows")
print("Full type distribution:")
print(train_df["type"].value_counts().to_string())

# Split the data into a "hard" pile and an "easy" pile according to HARD_TYPES
hard_mask = train_df["type"].isin(HARD_TYPES)
hard_df   = train_df[hard_mask].reset_index(drop=True)
easy_df   = train_df[~hard_mask].copy()  # Note: keep train_df's original row indices, we rely on them to locate rows later

# n = the count of the scarcest of the three hard types. It is the sampling
#     quota for each easy type, so that in the Nudge set the easy and hard
#     volumes are brought to the same order of magnitude and neither swamps the other.
n = int(hard_df["type"].value_counts().min())
print(f"\nHard type counts:")
print(hard_df["type"].value_counts().to_string())
print(f"\nn (samples per easy type for nudge set) = {n}")

# Randomly draw n samples from each easy type and record their original row indices in train_df (draw only easy, none of the hard)
rng = random.Random(SEED + 1)            # Use SEED+1 as a separate random source, decoupled from the shuffle above
nudge_easy_idx = set()                    # Set of easy-problem row indices "reserved for Nudge"
for etype, egroup in easy_df.groupby("type"):
    sampled = rng.sample(list(egroup.index), min(n, len(egroup)))   # Draw n from this type (take them all if fewer than n)
    nudge_easy_idx.update(sampled)
    print(f"  Easy '{etype}': sampled {len(sampled)}/{len(egroup)} for nudge set")

# ── Epoch1 set: all data minus the easy problems reserved for Nudge ───────────────────────
#    → equals: all hard problems + (all easy problems - those reserved for Nudge). Not a single hard problem is dropped.
epoch1_df = train_df[~train_df.index.isin(nudge_easy_idx)].reset_index(drop=True)

# ── Nudge set: all hard problems + the easy problems just drawn out ────────────────────────────────
nudge_easy_df = train_df[train_df.index.isin(nudge_easy_idx)]
nudge_df      = pd.concat([hard_df, nudge_easy_df]).reset_index(drop=True)

print(f"\nEpoch 1 set : {len(epoch1_df)} rows")
print("  Type distribution:", dict(sorted(epoch1_df["type"].value_counts().to_dict().items())))
print(f"\nNudge set   : {len(nudge_df)} rows")
print("  Type distribution:", dict(sorted(nudge_df["type"].value_counts().to_dict().items())))

# Guard the key invariant: the hard problems must appear in "full" in both sets (this is exactly what lets both phases train the hard problems heavily)
assert len(epoch1_df[epoch1_df["type"].isin(HARD_TYPES)]) == len(hard_df), "Hard problems missing from epoch1 set"
assert len(nudge_df[nudge_df["type"].isin(HARD_TYPES)])   == len(hard_df), "Hard problems missing from nudge set"
print("\nSanity checks passed.")


# %% [markdown]
# ## Training Infrastructure

# %%
# ════════════════════════════════════════════════════════════════════════════
#  Training infrastructure: sample construction + chat template + stratified sampler     see docs/solution.md §5, §6
# ════════════════════════════════════════════════════════════════════════════
import math, re
from collections import defaultdict
from datasets import Dataset as HFDataset
from trl import SFTTrainer, SFTConfig
from torch.utils.data import DataLoader, Sampler


def build_records(source_df):
    """Convert a dataframe into SFT samples, and return an equal-length list of type labels (for the stratified sampler).
    This function is the place in the whole file you can least afford to get wrong: a single wrong character in the format can drop answer extraction to 0 points at inference.  see §5
    """
    records, types = [], []
    for _, row in source_df.iterrows():
        cot = str(row["generated_cot"])
        # ① Data cleaning: the upstream-generated chain-of-thought may be empty / "nan" / nearly empty, so skip bad samples
        if not cot or cot == "nan" or len(cot.strip()) < 5:
            continue
        # ② Strip the \boxed{} that comes inside the chain-of-thought text: the final answer is re-assembled from the official answer, not trusting what upstream wrote
        #    (this decouples the "reasoning process" from the "final answer": process from upstream, answer from the official source)
        cot_cleaned = re.sub(r'\\boxed\{[^}]*\}', '', cot).rstrip()
        # ③ user side = problem + the forced suffix, aligning with the evaluation input
        user_content  = str(row["prompt"]) + PROMPT_SUFFIX
        # ④ assistant side = cleaned chain-of-thought + closing </think> + \boxed{} of the official answer
        #    Note: here we only add the "closing" </think>; the opening <think> is added automatically by the chat template below!
        #    Final target structure = <think>(added by template) ... chain-of-thought ... </think>(added here) \boxed{answer}(added here)
        #    This structure must match the evaluation protocol character for character, so that the model dutifully produces the same format at inference.
        asst_content  = cot_cleaned + f"\n</think>\n\\boxed{{{str(row['answer'])}}}"
        records.append({"messages": [
            {"role": "user",      "content": user_content},
            {"role": "assistant", "content": asst_content},
        ]})
        types.append(str(row["type"]))    # ⑤ Record each sample's type in parallel, to feed the stratified sampler
    return records, types


def formatting_prompts_func(example):
    """Wrap the messages in Nemotron's official chat template and convert them into plain text for training."""
    messages = example["messages"]
    # Support both single and batched input shapes, normalizing to a "list of conversations"
    if messages and isinstance(messages[0], dict):
        conversations = [messages]
    else:
        conversations = messages
    texts = []
    for conversation in conversations:
        try:
            text = tokenizer.apply_chat_template(
                conversation, tokenize=False,
                add_generation_prompt=False,   # This is training: we want the full conversation (including the answer) as the target, not to stop and wait for a continuation
                enable_thinking=True)          # Turn on thinking mode: the template will automatically insert <think> before the assistant
        except TypeError:
            # Fallback: older tokenizer versions do not recognize the enable_thinking argument
            text = tokenizer.apply_chat_template(
                conversation, tokenize=False, add_generation_prompt=False)
        texts.append(text)
    return texts


def build_stratified_index_order(labels, batch_size, seed):
    """Precompute a "type-balanced" sample order: make each effective batch contain a bit of every type as much as possible,
    avoiding the gradient-direction jitter that comes from a batch made entirely of one problem type. Core technique = dealing cards (round-robin).  see §6
    """
    # 1) Bucket sample indices by type
    by_label = defaultdict(list)
    for idx, label in enumerate(labels):
        by_label[label].append(idx)
    # 2) Shuffle each bucket internally (consumes the seed, reproducible)
    rng = random.Random(seed)
    for idx_list in by_label.values():
        rng.shuffle(idx_list)
    # 3) Prepare n_batches empty batch buckets, and shuffle the "bucket fill order" too
    n_batches = max(1, math.ceil(len(labels) / batch_size))
    batches   = [[] for _ in range(n_batches)]
    b_order   = list(range(n_batches))
    rng.shuffle(b_order)
    # 4) Deal: scatter each type's samples one by one (modulo) into the batch buckets in turn
    #    → like dealing cards, dealing one suit card by card to N players, then dealing the next suit → every bucket has every suit
    assigned  = 0
    for label in sorted(by_label.keys()):
        for idx in by_label[label]:
            batches[b_order[assigned % n_batches]].append(idx)
            assigned += 1
    # 5) Flatten all batch buckets into a one-dimensional order and return it
    order = [idx for batch in batches for idx in batch]
    if len(order) != len(labels):
        raise ValueError("Stratified order size mismatch")
    return order


class PrecomputedOrderSampler(Sampler):
    """A "take it as given" sampler: emit sample indices strictly in the given fixed order, doing no shuffling at all."""
    def __init__(self, order): self.order = list(order)
    def __iter__(self):        return iter(self.order)
    def __len__(self):         return len(self.order)


class StratifiedSFTTrainer(SFTTrainer):
    """An SFTTrainer that overrides only get_train_dataloader: feed the precomputed balanced order into the DataLoader,
    inheriting everything else from TRL's SFTTrainer (a minimal change surface, without hacking TRL's internal shuffling logic).
    """
    def __init__(self, *args, stratified_order=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.stratified_order = stratified_order

    def get_train_dataloader(self):
        if self.stratified_order is None:
            return super().get_train_dataloader()     # No order given, fall back to TRL's default behavior
        if len(self.stratified_order) != len(self.train_dataset):
            raise ValueError("Stratified order length does not match train dataset")
        # Build a DataLoader ourselves; the key is that the sampler uses the "take it as given" fixed-order sampler above
        dataloader_kwargs = {
            "batch_size":         self.args.per_device_train_batch_size,
            "sampler":            PrecomputedOrderSampler(self.stratified_order),  # ← the balanced order takes effect here
            "collate_fn":         self.data_collator,
            "num_workers":        self.args.dataloader_num_workers,
            "pin_memory":         self.args.dataloader_pin_memory,
            "persistent_workers": self.args.dataloader_persistent_workers,
            "drop_last":          self.args.dataloader_drop_last,
        }
        if self.args.dataloader_num_workers > 0:
            dataloader_kwargs["prefetch_factor"] = self.args.dataloader_prefetch_factor
        return DataLoader(self.train_dataset, **dataloader_kwargs)


print("Training infrastructure ready.")


# %% [markdown]
# ## Phase 1: Train
#
# Train on "all hard problems + the easy problems not held out for nudging".

# %%
# ════════════════════════════════════════════════════════════════════════════
#  Phase 1 "Train": large learning rate + gradient clipping off, aggressive coarse training for coverage   see docs/solution.md §7
# ════════════════════════════════════════════════════════════════════════════
import gc, time

# Build samples from the Epoch1 set (§5) and convert them to an HF Dataset
epoch1_records, epoch1_types = build_records(epoch1_df)
epoch1_dataset = HFDataset.from_list(epoch1_records)
print(f"Epoch 1 records: {len(epoch1_records)}")
print("Type distribution:", dict(sorted(pd.Series(epoch1_types).value_counts().to_dict().items())))

training_args = SFTConfig(
    output_dir="/kaggle/working/phase1_output",
    num_train_epochs=TRAIN_EPOCHS,
    per_device_train_batch_size=TRAIN_BATCH,
    gradient_accumulation_steps=TRAIN_GRAD_ACCUM,
    learning_rate=TRAIN_LR,             # 2e-4 large learning rate
    lr_scheduler_type="linear",         # Linear decay
    warmup_steps=0,                     # No warmup: only 1 epoch, full speed from the start
    max_length=8192,                    # Truncate over-long samples to 8192, matching the inference window
    adam_beta1=0.9,
    adam_beta2=0.95,                    # Smaller than the default 0.999: shorter momentum memory, more sensitive to recent gradients (common for LLMs)
    adam_epsilon=1e-8,
    weight_decay=0.0,                   # No weight decay
    max_grad_norm=1e9,                  # ★ 1 billion = effectively disable gradient clipping: Phase 1 is not afraid of big steps, aggressiveness is exactly what we want  §7④
    logging_steps=50,
    save_strategy="no",                 # No checkpoints during training (save manually at the end)
    bf16=True,
    gradient_checkpointing=True,        # Save memory (trade time for memory)
    gradient_checkpointing_kwargs={"use_reentrant": False},
    dataloader_num_workers=2,
    remove_unused_columns=False,        # Keep the custom column (messages), do not let TRL drop it automatically
    seed=SEED,
    report_to="none",                   # Do not report to wandb etc.
    packing=False,                      # ★ No packing: prevent tokens of different problems from cross-contaminating across samples, keep clean sample boundaries  §7⑥
    neftune_noise_alpha=5.0,            # ★ NEFTune: embedding noise regularization, resisting rote memorization of trivia  see §7 term expansion
)

# Effective batch = 1×8 = 8; compute the type-balanced sample order from it (§6)
eff_batch_1   = TRAIN_BATCH * TRAIN_GRAD_ACCUM
strat_order_1 = build_stratified_index_order(epoch1_types, eff_batch_1, SEED)
print(f"Effective batch size: {eff_batch_1}")

trainer_phase1 = StratifiedSFTTrainer(
    model=model,
    args=training_args,
    train_dataset=epoch1_dataset,
    processing_class=tokenizer,
    formatting_func=formatting_prompts_func,
    stratified_order=strat_order_1,     # Feed the balanced order into the custom Trainer
)

print("\nStarting Phase 1 training ...")
t0 = time.time()
trainer_phase1.train()
elapsed1 = time.time() - t0
print(f"Phase 1 done in {elapsed1/60:.1f} min")

# After training, clear GPU memory to make room for Phase 2
gc.collect()
import torch; torch.cuda.empty_cache()


# %%
# Save the Phase 1 adapter once on its own. Two purposes: ① insurance (if Phase 2 trains into a wreck, fall back to this);
# ② treat "Phase 1 only" as a submittable comparison candidate, to make A/B of single-phase vs two-phase easy.  see end of §7
PHASE1_ADAPTER_DIR = "/kaggle/working/phase1_adapter"
model.save_pretrained(PHASE1_ADAPTER_DIR)
tokenizer.save_pretrained(PHASE1_ADAPTER_DIR)
print(f"Phase 1 adapter saved to {PHASE1_ADAPTER_DIR}")
for fname in os.listdir(PHASE1_ADAPTER_DIR):
    fpath = os.path.join(PHASE1_ADAPTER_DIR, fname)
    print(f"  {fname}: {os.path.getsize(fpath)/1024/1024:.1f} MB")

# %% [markdown]
# ## Phase 2: Nudge
#
# With an ultra-low LR, nudge the already-trained adapter on "all hard problems + n easy problems of each type".

# %%
# ⚠️ This whole block is commented out with triple quotes = an experiment the author tried but ultimately abandoned.  see docs/solution.md §8.4
#    The idea: during Phase 2 (refinement), raise the LoRA dropout from 0 to 0.1, adding some regularization to prevent overfitting.
#    Ultimately not enabled → Phase 2's regularization relies only on NEFTune + a small lr, with no dropout.
#    Retrospective value: this is a ready-made, restartable comparison experiment.
"""# ── Set dropout to 0.1 for nudge phase ───────────────────────────────────────
import torch.nn as nn

_updated = 0
for _name, _module in model.named_modules():
    if hasattr(_module, 'lora_dropout') and isinstance(_module.lora_dropout, nn.ModuleDict):
        for _adapter_name in _module.lora_dropout.keys():
            _module.lora_dropout[_adapter_name] = nn.Dropout(p=0.1)
            _updated += 1

if _updated == 0:
    raise RuntimeError("No LoRA dropout layers found — check model structure before proceeding.")

print(f"LoRA dropout set to 0.1 on {_updated} layers.")"""

# %%
# ════════════════════════════════════════════════════════════════════════════
#  Phase 2 "Nudge": ultra-low lr + gradient clipping on, refine on hard problems while preventing forgetting of easy ones  see §8
#  Note: continue training on the "same model" left after Phase 1, with LoRA weights carrying on from Phase 1, no reload.
# ════════════════════════════════════════════════════════════════════════════
import gc, time

# Build samples from the Nudge set (§4: all hard problems + n fresh easy samples per type, type-balanced)
nudge_records, nudge_types = build_records(nudge_df)
nudge_dataset = HFDataset.from_list(nudge_records)
print(f"Nudge records: {len(nudge_records)}")
print("Type distribution:", dict(sorted(pd.Series(nudge_types).value_counts().to_dict().items())))

# Compared with Phase 1, the differences are all about "stay stable + refine" (see the §8 comparison table):
nudge_args = SFTConfig(
    output_dir="/kaggle/working/phase2_output",
    num_train_epochs=NUDGE_EPOCHS,
    per_device_train_batch_size=NUDGE_BATCH,
    gradient_accumulation_steps=NUDGE_GRAD_ACCUM,
    learning_rate=NUDGE_LR,             # ★ 5e-6, 1/40 of Phase 1: only fine-tune, do not overturn what was already learned
    lr_scheduler_type="cosine",         # ★ Cosine decay, a smooth wind-down (a typical "cooldown" phase)
    warmup_steps=10,                    # ★ Add a little warmup, more stable in the refinement phase
    max_length=8192,
    adam_beta1=0.9,
    adam_beta2=0.95,
    adam_epsilon=1e-8,
    weight_decay=0.0,
    max_grad_norm=1.0,                  # ★ Re-enable gradient clipping (vs Phase 1's 1e9): rein in gradients to prevent damage
    logging_steps=5,                    # Watch more closely (small data volume)
    save_strategy="no",
    bf16=True,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    dataloader_num_workers=2,
    remove_unused_columns=False,
    seed=SEED,
    report_to="none",
    packing=False,
    neftune_noise_alpha=5.0,            # NEFTune on in both phases, kept consistent
)

eff_batch_2   = NUDGE_BATCH * NUDGE_GRAD_ACCUM
strat_order_2 = build_stratified_index_order(nudge_types, eff_batch_2, SEED)
print(f"Effective batch size: {eff_batch_2}")

trainer_phase2 = StratifiedSFTTrainer(
    model=model,                        # ← the same model, continuing on from Phase 1
    args=nudge_args,
    train_dataset=nudge_dataset,
    processing_class=tokenizer,
    formatting_func=formatting_prompts_func,
    stratified_order=strat_order_2,
)

print("\nStarting Phase 2 nudge ...")
t0 = time.time()
trainer_phase2.train()
elapsed2 = time.time() - t0
print(f"Phase 2 done in {elapsed2/60:.1f} min")

gc.collect()
import torch; torch.cuda.empty_cache()


# %% [markdown]
# ## Save & Package

# %%
# ════════════════════════════════════════════════════════════════════════════
#  Save the final adapter + patch it + package submission.zip    see docs/solution.md §9
# ════════════════════════════════════════════════════════════════════════════
import json, os, shutil, zipfile

ADAPTER_DIR = "/kaggle/working/final_adapter"
model.save_pretrained(ADAPTER_DIR)        # Saves the final LoRA after Phase 1+2
tokenizer.save_pretrained(ADAPTER_DIR)
print(f"Adapter saved to {ADAPTER_DIR}")

# ── patch adapter_config.json: without changing this, the evaluation side will simply crash ──────────────────
cfg_path = os.path.join(ADAPTER_DIR, "adapter_config.json")
with open(cfg_path) as f:
    cfg = json.load(f)
# ① During training this field may have been written as a local cache path that
#    does not exist on the evaluation machine → it must be written back to the
#    official base-model name so that vLLM can correctly attach the adapter to
#    the host-provided base model. (The single most critical pitfall.)
cfg["base_model_name_or_path"] = BASE_MODEL_NAME
cfg["inference_mode"] = True              # ② Mark it as inference mode
cfg["lora_dropout"]   = 0.0              # ③ Inference dropout must be 0, to prevent any residual randomness
with open(cfg_path, "w") as f:
    json.dump(cfg, f, indent=2)

# ── Package: include only the two files required by the rules, without the base weights (the base model is provided on the evaluation side) ──────────
zip_path = "/kaggle/working/submission.zip"
required  = ["adapter_config.json", "adapter_model.safetensors"]  # The submission artifact is just these two
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
    for fname in required:
        fpath = os.path.join(ADAPTER_DIR, fname)
        if not os.path.exists(fpath):
            raise FileNotFoundError(f"Missing: {fpath}")    # Fail early if a file is missing, do not submit a broken package
        zf.write(fpath, fname)
        print(f"  Added {fname} ({os.path.getsize(fpath)/1024/1024:.1f} MB)")

print(f"\nsubmission.zip: {os.path.getsize(zip_path)/1024/1024:.1f} MB")
print("Done! Ready to submit.")


# %%
# ── Clean up the working directory ───────────────────────────────────────────────────────
#  Kaggle caps the size of artifacts under /kaggle/working, so delete intermediate artifacts and keep only what is needed.
import os, shutil, glob

KEEP = {
    "/kaggle/working/submission.zip",     # The final submission package
    "/kaggle/working/phase1_adapter",     # Keep the Phase 1 adapter as a comparison candidate (see end of §7)
}

for path in glob.glob("/kaggle/working/*"):
    if path in KEEP:
        continue
    try:
        if os.path.isdir(path):
            shutil.rmtree(path)
        else:
            os.remove(path)
        print(f"Deleted: {path}")
    except Exception as e:
        print(f"Could not delete {path}: {e}")    # If it cannot be deleted, skip it, do not let the cleanup step interrupt the flow

print("\nRemaining files:")
for path in glob.glob("/kaggle/working/*"):
    print(f"  {path} ({os.path.getsize(path):,} bytes)")

# %%



